import { describe, expect, it } from "vitest";
import { categorizeFile } from "../../../src/ingest/ignore.js";

describe("categorizeFile — binary", () => {
  it("returns 'binary' when the binary flag is set, with top precedence", () => {
    expect(categorizeFile("assets/logo.png", undefined, true, [])).toBe("binary");
    // binary wins over lockfile/generated/user globs
    expect(categorizeFile("package-lock.json", "auto-generated", true, ["**/*"])).toBe(
      "binary",
    );
  });
});

describe("categorizeFile — lockfiles", () => {
  it("matches every known lockfile basename (§11.2)", () => {
    const lockfiles = [
      "package-lock.json",
      "yarn.lock",
      "pnpm-lock.yaml",
      "Cargo.lock",
      "poetry.lock",
      "Gemfile.lock",
      "composer.lock",
    ];
    for (const name of lockfiles) {
      expect(categorizeFile(name, undefined, false, [])).toBe("lockfile");
      expect(categorizeFile(`packages/app/${name}`, undefined, false, [])).toBe(
        "lockfile",
      );
    }
  });

  it("does not match lookalikes", () => {
    expect(categorizeFile("package.json", undefined, false, [])).toBeNull();
    expect(categorizeFile("src/package-lock.json.ts", undefined, false, [])).toBeNull();
  });
});

describe("categorizeFile — generated markers", () => {
  it("matches 'Code generated … DO NOT EDIT' on the first line", () => {
    expect(
      categorizeFile("src/gen/api.ts", "// Code generated by protoc-gen-ts. DO NOT EDIT.", false, []),
    ).toBe("generated");
  });

  it("matches '@generated' and 'auto-generated' on the first line", () => {
    expect(categorizeFile("src/gen/out.js", "// @generated by tool", false, [])).toBe(
      "generated",
    );
    expect(categorizeFile("src/gen/out.js", "/* auto-generated — do not touch */", false, [])).toBe(
      "generated",
    );
  });

  it("ignores markers beyond the first line (undefined first line)", () => {
    expect(categorizeFile("src/index.ts", undefined, false, [])).toBeNull();
  });
});

describe("categorizeFile — generated conventional paths", () => {
  it("matches dist/, build/, *.min.js, *.map, *.pb.go, *.snap, __snapshots__/", () => {
    const generated = [
      "dist/bundle.js",
      "packages/web/dist/app.js",
      "build/output.js",
      "packages/lib/build/index.js",
      "assets/app.min.js",
      "dist/app.js.map",
      "src/proto/service.pb.go",
      "tests/foo.snap",
      "src/__snapshots__/button.test.tsx.snap",
      "__snapshots__/x.js",
    ];
    for (const p of generated) {
      expect(categorizeFile(p, "ordinary source", false, [])).toBe("generated");
    }
  });

  it("does not match normal source paths", () => {
    const normal = [
      "src/index.ts",
      "src/components/Button.tsx",
      "src/dist-utils/helper.ts",
      "docs/building.md",
      "src/map.ts",
    ];
    for (const p of normal) {
      expect(categorizeFile(p, "ordinary source", false, [])).toBeNull();
    }
  });
});

describe("categorizeFile — user globs", () => {
  it("matches user-provided picomatch globs", () => {
    expect(categorizeFile("fixtures/data.json", "x", false, ["fixtures/**"])).toBe(
      "user-ignore",
    );
    expect(categorizeFile("src/api.generated.ts", "x", false, ["**/*.generated.ts"])).toBe(
      "user-ignore",
    );
  });

  it("returns null when no glob matches", () => {
    expect(categorizeFile("src/index.ts", "x", false, ["fixtures/**"])).toBeNull();
    expect(categorizeFile("src/index.ts", "x", false, [])).toBeNull();
  });
});
